src/Cipen/PrestacionBundle/Entity/ActoUnidad.php
<?php

namespace Cipen\PrestacionBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as assert;

/**
 * Cipen\PrestacionBundle\Entity\Nomenclador
 *
 * @ORM\Table("Prestacion__Acto_Unidad")
 * @ORM\Entity(repositoryClass="Cipen\PrestacionBundle\Entity\ActoUnidadRepository")
 */
class ActoUnidad
{
    const NOMENCLADOR_PMOE = 'PMOE' ;
    const NOMENCLADOR_BIOQUIMICO = 'BIOQUIMICO' ;
    const SIN_NOMENCLADOR = 'SIN_NOMENCLADOR' ;
    
    public static $tiposNomenclador = array(
        self::NOMENCLADOR_PMOE => 'PMOE',
        self::NOMENCLADOR_BIOQUIMICO => 'BIOQUÍMICO ÚNICO NBU - PMO',
        self::SIN_NOMENCLADOR => 'SIN NOMENCLADOR'
    );

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="Cipen\PrestacionBundle\Entity\Acto", inversedBy="actoUnidades")
     */
    private $acto;
    
    /**
     * @ORM\ManyToOne(targetEntity="Cipen\ObraSocialBundle\Entity\ObraSocial")
     * @assert\NotNull(message="Seleccione Obra Social")
     */
    private $obraSocial;    

    /**
     * @ORM\ManyToOne(targetEntity="Cipen\ObraSocialBundle\Entity\Unidad")
     * @ORM\JoinColumn(name="unidad_honorario_id",nullable=true)
     * @assert\NotNull(message="Seleccione unidad para honorario", groups={"unidad"})
     */
    private $unidadHonorario;    
    
    /**
     * @ORM\ManyToOne(targetEntity="Cipen\ObraSocialBundle\Entity\Unidad")
     * @ORM\JoinColumn(name="unidad_gasto_id", nullable=true)
     * @assert\NotNull(message="Seleccione unidad para gasto", groups={"unidad"})
     */
    private $unidadGasto;        
    
    /**
     * @ORM\Column(name="nomenclador", type="string")
     */
    private $nomenclador;
    
    /**
     * @var float $honorariroEspecialista
     *
     * @ORM\Column(name="honorarioEspecialista", type="float")
     * @assert\NotBlank(message="Por favor, ingrese honorarios para especialista")
     */
    private $honorarioEspecialista;
    

    /**
     * @var float $honorarioAyudante
     *
     * @ORM\Column(name="honorarioAyudante", type="float")
     * @assert\NotBlank(message="Por favor, ingrese honorarios para ayudante")
     */
    private $honorarioAyudante;


    /**
     * @var float $honorarioAnestesista
     *
     * @ORM\Column(name="honorarioAnestesista", type="float")
     * @assert\NotBlank(message="Por favor, ingrese honorarios para anestesista")
     */
    private $honorarioAnestesista;

    
    /**
     * @var float $gasto
     *
     * @ORM\Column(name="gasto", type="float")
     * @assert\NotBlank(message="Por favor, ingrese gasto")
     */
    private $gasto;
    

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nomenclador
     *
     * @param string $nomenclador
     * @return ActoUnidad
     */
    public function setNomenclador($nomenclador)
    {
        $this->nomenclador = $nomenclador;
    
        return $this;
    }

    /**
     * Get nomenclador
     *
     * @return string 
     */
    public function getNomenclador()
    {
        return $this->nomenclador;
    }
    
    public function getNomencladorDescripcion()
    {
        return self::$tiposNomenclador[$this->nomenclador];
    }

    /**
     * Set honorarioEspecialista
     *
     * @param float $honorarioEspecialista
     * @return ActoUnidad
     */
    public function setHonorarioEspecialista($honorarioEspecialista)
    {
        $this->honorarioEspecialista = $honorarioEspecialista;
    
        return $this;
    }

    /**
     * Get honorarioEspecialista
     *
     * @return float 
     */
    public function getHonorarioEspecialista()
    {
        return $this->honorarioEspecialista;
    }


    /**
     * Set honorarioAyudante
     *
     * @param float $honorarioAyudante
     * @return ActoUnidad
     */
    public function setHonorarioAyudante($honorarioAyudante)
    {
        $this->honorarioAyudante = $honorarioAyudante;
    
        return $this;
    }

    /**
     * Get honorarioAyudante
     *
     * @return float 
     */
    public function getHonorarioAyudante()
    {
        return $this->honorarioAyudante;
    }

    /**
     * Set honorarioAnestesista
     *
     * @param float $honorarioAnestesista
     * @return ActoUnidad
     */
    public function setHonorarioAnestesista($honorarioAnestesista)
    {
        $this->honorarioAnestesista = $honorarioAnestesista;
    
        return $this;
    }

    /**
     * Get honorarioAnestesista
     *
     * @return float 
     */
    public function getHonorarioAnestesista()
    {
        return $this->honorarioAnestesista;
    }

    /**
     * Set gasto
     *
     * @param float $gasto
     * @return ActoUnidad
     */
    public function setGasto($gasto)
    {
        $this->gasto = $gasto;
    
        return $this;
    }

    /**
     * Get gasto
     *
     * @return float 
     */
    public function getGasto()
    {
        return $this->gasto;
    }

    /**
     * Set acto
     *
     * @param \Cipen\PrestacionBundle\Entity\Acto $acto
     * @return ActoUnidad
     */
    public function setActo(\Cipen\PrestacionBundle\Entity\Acto $acto = null)
    {
        $this->acto = $acto;
    
        return $this;
    }

    /**
     * Get acto
     *
     * @return \Cipen\PrestacionBundle\Entity\Acto 
     */
    public function getActo()
    {
        return $this->acto;
    }
    

    /**
     * Set obraSocial
     *
     * @param \Cipen\ObraSocialBundle\Entity\ObraSocial $obraSocial
     * @return ActoUnidad
     */
    public function setObraSocial(\Cipen\ObraSocialBundle\Entity\ObraSocial $obraSocial = null)
    {
        $this->obraSocial = $obraSocial;
    
        return $this;
    }

    /**
     * Get obraSocial
     *
     * @return \Cipen\ObraSocialBundle\Entity\ObraSocial 
     */
    public function getObraSocial()
    {
        return $this->obraSocial;
    }

    /**
     * Set unidadHonorario
     *
     * @param \Cipen\ObraSocialBundle\Entity\Unidad $unidadHonorario
     * @return ActoUnidad
     */
    public function setUnidadHonorario(\Cipen\ObraSocialBundle\Entity\Unidad $unidadHonorario = null)
    {
        $this->unidadHonorario = $unidadHonorario;
    
        return $this;
    }

    /**
     * Get unidadHonorario
     *
     * @return \Cipen\ObraSocialBundle\Entity\Unidad 
     */
    public function getUnidadHonorario()
    {
        return $this->unidadHonorario;
    }

    /**
     * Set unidadGasto
     *
     * @param \Cipen\ObraSocialBundle\Entity\Unidad $unidadGasto
     * @return ActoUnidad
     */
    public function setUnidadGasto(\Cipen\ObraSocialBundle\Entity\Unidad $unidadGasto = null)
    {
        $this->unidadGasto = $unidadGasto;
    
        return $this;
    }

    /**
     * Get unidadGasto
     *
     * @return \Cipen\ObraSocialBundle\Entity\Unidad 
     */
    public function getUnidadGasto()
    {
        return $this->unidadGasto;
    }
    
    /**
     * @Assert\True(message="El acto médico ya tiene ésta obra social asociada.")
     */
    public function isObraSocialValida()
    {
        if($this->getObraSocial ()){
            $actoUnidades = $this->getActo()->getActoUnidades();
            foreach($actoUnidades as $actoUnidad){
                if ($actoUnidad->getObraSocial()->getId() == $this->getObraSocial ()->getId() and $actoUnidad->getId() != $this->getId() )   {
                    return false;
                }
            }
        }
        return true;
    }       
    
}

src/Cipen/PrestacionBundle/Controller/ActoUnidadController.php
<?php

namespace Cipen\PrestacionBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;

use Cipen\PrestacionBundle\Entity\ActoUnidad;
use Cipen\PrestacionBundle\Form\ActoUnidadType;

/**
 * Paciente controller.
 *
 */
class ActoUnidadController extends Controller
{
    /**
     * Lists all Paciente entities.
     *
     */
    public function listarAction($actoId = 0)
    {
    	$em = $this->getDoctrine()->getEntityManager();
        $datos["entities"] = $em->getRepository('CipenPrestacionBundle:ActoUnidad')->findByActo($actoId);
        
        $datos['actoId'] = $actoId;
        
    	return $this->render('CipenPrestacionBundle:ActoUnidad:listar.html.twig',$datos);
    
    }

    
    /**
     * Displays a form to create a new Paciente entity.
     *
     */
    public function crearAction($actoId = 0, Request $request)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $entity = new ActoUnidad();
        
        $acto = $em->getRepository ('CipenPrestacionBundle:Acto')->find ($actoId) ;        
        if (! $acto) {
            $this->createNotFoundException("No se encontro acto médico");
        }

        $entity->setActo($acto);
        
        if ($request->isMethod("POST")) {
            
            $form = $this->createForm(new ActoUnidadType(), $entity);
            $form->bind($request);
            
            if ($form->isValid ()) {
                                
                $entity = $this->setUnidades($entity);
                $em->persist($entity);
                $em->flush();
                
                $request->getSession()->getFlashBag()->add('alert-success','Se agrego obra social con éxito.');
                
                return $this->redirect($this->generateUrl('acto_unidad_editar',array('actoId'=>$actoId,'id'=>$entity->getId())));
                
            }
            
            $request->getSession()->getFlashBag()->add('alert-error','ERROR! No se pudo agregar obra social.');            
            
        } else {
            
            // precarga honorarios, cantidades y gasto si existe un PMOE cargado anteriormente
            $actoUnidadPMOEAnterior = $em->getRepository("CipenPrestacionBundle:ActoUnidad")->findOneBy(array('acto'=>$actoId, 'nomenclador'=>'PMOE'),array('id'=>'DESC'));
            
            if ($actoUnidadPMOEAnterior) {
                
                $entity->setHonorarioAnestesista($actoUnidadPMOEAnterior->getHonorarioAnestesista());
                $entity->setHonorarioAyudante($actoUnidadPMOEAnterior->getHonorarioAnestesista());
                $entity->setHonorarioEspecialista($actoUnidadPMOEAnterior->getHonorarioEspecialista());
                
                $entity->setGasto($actoUnidadPMOEAnterior->getGasto());
                
            }
            
            $form = $this->createForm(new ActoUnidadType(), $entity);
            
        }

        $datos["actoId"] = $actoId;
        $datos["entity"] = $entity;
        $datos["form"] = $form->createView ();
        return $this->render('CipenPrestacionBundle:ActoUnidad:nuevo.html.twig', $datos);
    }

    /**
     * Creates a new Paciente entity.
     *
     */
    public function editarAction($actoId, $id, Request $request)
    {
        $em = $this->getDoctrine()->getEntityManager();
                
        $entity = $em->getRepository ('CipenPrestacionBundle:ActoUnidad')->find ($id) ;        
        if (! $entity) {
            $this->createNotFoundException("No se encontro acto unidad");
        }
        
        $form   = $this->createForm(new ActoUnidadType(), $entity);
        
        if ($request->isMethod ("POST")) {
            
            $form->bind($request);
            
            if ($form->isValid ()) {
                
                $entity = $this->setUnidades($entity);
                $em->persist($entity);
                $em->flush();
                
                $request->getSession()->getFlashBag()->add('alert-success','Se actualizo obra social con éxito.');                             return $this->redirect($this->generateUrl('acto_unidad_editar',array('actoId'=>$actoId,'id'=>$entity->getId())));  
            }
            
                      
        }

        $datos["actoId"] = $actoId;
        $datos["entity"] = $entity;
        $datos["form"] = $form->createView ();
        
        return $this->render('CipenPrestacionBundle:ActoUnidad:editar.html.twig', $datos);    
       
    }

  
    private function setUnidades ($entity) 
    {
        if ($entity->getNomencladorDescripcion() == "SIN_NOMENCLADOR") {
            $entity->setUnidadHonorario(null);
            $entity->setUnidadGasto(null);                    
        }
        
        return $entity;
    }

    /**
     * Deletes a Paciente entity.
     *
     */
    public function eliminarAction($actoId,$id, Request $request)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $entity = $em->getRepository('CipenPrestacionBundle:ActoUnidad')->find($id);

        if (!$entity) {
        throw $this->createNotFoundException('No se encontro registro.');
        }

        $em->remove($entity);
        $em->flush();
        
        $request->getSession()->getFlashBag()->add('alert-success','Se quito obra social de acto médico con éxito.'); 

        return $this->redirect($this->generateUrl('acto_unidad',array('actoId'=>$actoId)));
    }
    
    public function ajaxAutocompleteAction(Request $request)
    {        
        $actoUnidadRepository = $this->getDoctrine()->getRepository('CipenPrestacionBundle:ActoUnidad');
        $actosUnidades = $actoUnidadRepository->
                                       createQueryBuilderForSearchAutocomplete(
                                           $request->query->get('term'),
                                           $request->query->get('obraSocial')
                                        )
                                        ->getQuery()->getResult();

        $data = array();
        foreach ($actosUnidades as $actoUnidad){
            
            if($actoUnidad->getActo()->getCodigo()){
                $label =  $actoUnidad->getActo()->getCodigo()." - ".$actoUnidad->getActo()->getDescripcion();
            } else {
                $label =  $actoUnidad->getActo()->getDescripcion();
            }
            
            $data[] = array($actoUnidad->getId(), $label);
        }

        return JsonResponse::create($data);        
    }
       

}

src/Cipen/PrestacionBundle/Resources/views/ActoUnidad/_form.html.twig
{{ form_errors (form) }}

<div class="control-group">
    {{ form_label(form.nomenclador,'Tipo de Nomenclador',{ label_attr : { class : 'control-label'} }) }} 
    <div class="controls">
        {{ form_widget (form.nomenclador, { attr : { class : 'span7' } }) }}
        {{ form_errors (form.nomenclador) }}
    </div>
</div>               

<div class="control-group" data-campo-group="obraSocial" >
    {{ form_label(form.obraSocial,'Obra Social *',{ label_attr : { class : 'control-label'} }) }} 
    <div class="controls">
        {{ form_widget (form.obraSocial, { attr : { class : 'span7' } }) }}
        {{ form_errors (form.obraSocial) }}
    </div>
</div>  

<div class="control-group {{ entity.obraSocial is empty or entity.nomenclador == "SIN_NOMENCLADOR" ? "hide" : "" }}" data-id="control-group-unidad">
    {{ form_label(form.unidadHonorario,'Unidad honorario *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.unidadHonorario, { attr : { class : 'span7' } }) }}
        {{ form_errors (form.unidadHonorario) }}
    </div>
</div>  

<div class="control-group {{ entity.obraSocial is empty or entity.nomenclador == "SIN_NOMENCLADOR" ? "hide" : "" }}" data-id="control-group-unidad">
    {{ form_label(form.unidadGasto,'Unidad gasto *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.unidadGasto, { attr : { class : 'span7' } }) }}
        {{ form_errors (form.unidadGasto) }}
    </div>
</div>  

<hr>

<div class="control-group">
    {{ form_label(form.honorarioEspecialista,'Honorario especialista *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.honorarioEspecialista, { attr : { class : 'span4' } }) }}
        {{ form_errors (form.honorarioEspecialista) }}
    </div>
</div> 

<div class="control-group">
    {{ form_label(form.honorarioAyudante,'Honorario ayudante *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.honorarioAyudante, { attr : { class : 'span4' } }) }}
        {{ form_errors (form.honorarioAyudante) }}
    </div>
</div> 

<div class="control-group">
    {{ form_label(form.honorarioAnestesista,'Honorario anestesista *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.honorarioAnestesista, { attr : { class : 'span4' } }) }}
        {{ form_errors (form.honorarioAnestesista) }}
    </div>
</div> 

<div class="control-group">
    {{ form_label(form.gasto,'Gasto *',{ label_attr : { class : 'control-label'} }) }}
    <div class="controls">
        {{ form_widget (form.gasto, { attr : { class : 'span4' } }) }}
        {{ form_errors (form.gasto) }}
    </div>
</div> 


{{ form_rest (form) }}


<script type="text/javascript">
    
    var urlGetUnidadesPorObraSocial = "{{ path('obra_social_unidad_get_por_obra_social') }}"
    
</script>

src/Cipen/PrestacionBundle/Resources/views/ActoUnidad/editar.html.twig
{% extends "CipenPrestacionBundle:Acto:editar_layout.html.twig" %}
 
{% block admin_content %}

    <ul class="nav nav-tabs">
        <li><a href="{{ path('acto_editar', { id: actoId }) }}">Datos acto médico</a></li>
        <li><a href="{{ path('acto_unidad', { actoId: actoId }) }}">Obras Sociales</a></li>
        <li class="active"><a href="{{ path('acto_unidad_editar', { actoId: actoId, id: entity.id }) }}">Editar Obra Social</a></li>
    </ul>  
    
    <div class="well well-small">
        <a href="{{ path('acto_unidad_crear', { actoId : actoId }) }}"><i class="icon-plus"></i> Agregar Obra Social</a>
    </div>
        
    <form novalidate="true" class="form-horizontal" method="POST" action="{{ path('acto_unidad_editar', { actoId: actoId, id: entity.id }) }}">

        {% include 'CipenPrestacionBundle:ActoUnidad:_form.html.twig' %}        
        
        <div class="form-actions">
            <button class="btn btn-success pull-right" type="submit">Guardar</button>
        </div>
        
    </form>
    
{% endblock %}

src/Cipen/PrestacionBundle/Resources/views/ActoUnidad/listar.html.twig
{% extends "CipenPrestacionBundle:Acto:editar_layout.html.twig" %}
            
{% block admin_content %}

   <ul class="nav nav-tabs">
        <li><a href="{{ path('acto_editar', { id: actoId }) }}">Datos de acto médico</a></li>
        <li class="active"><a href="{{ path('acto_unidad', { actoId: actoId }) }}">Obras Sociales</a></li>
    </ul>    
    
    <div class="well well-small">
        <a href="{{ path('acto_unidad_crear', { actoId : actoId }) }}"><i class="icon-plus"></i> Agregar Obra Social</a>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Obra Social</th>
                <th>Tipo Nomenclador</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td>{{ entity.obraSocial.nombre }}</td>
                    <td>{{ entity.nomencladorDescripcion }}</td>
                    <td>
                        <div style="margin:0; padding:0;" class="btn-toolbar pull-right">
                            <a class="btn" href="{{ path('acto_unidad_editar', {actoId: actoId, id: entity.id }) }}" title="Editar" >
                                <i class="icon-pencil"></i>
                            </a>
                            <a class="btn btn-danger" onclick="if(!confirm('¿Seguro desea eliminar esta unidad?')){ return false }" href="{{ path('acto_unidad_eliminar', {actoId: actoId, id: entity.id}) }}" title="Eliminar" >
                                <i class="icon-white icon-trash"></i>
                            </a>                                
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="2">No existen registros</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    
{% endblock %}

src/Cipen/PrestacionBundle/Resources/views/ActoUnidad/nuevo.html.twig
{% extends "CipenPrestacionBundle:Acto:editar_layout.html.twig" %}
    
{% block admin_content %}

    <ul class="nav nav-tabs">
        <li><a href="{{ path('acto_editar', { id: actoId }) }}">Datos acto médico</a></li>
        <li><a href="{{ path('acto_unidad', { actoId: actoId }) }}">Obras Sociales</a></li>
        <li class="active"><a href="{{ path('acto_unidad_crear', { actoId: actoId }) }}">Agregar Obra Social</a></li>
    </ul>        
    
    <form novalidate="true" class="form-horizontal" method="POST" action="{{ path('acto_unidad_crear', { actoId: actoId }) }}" >

        {% include 'CipenPrestacionBundle:ActoUnidad:_form.html.twig' %}               
        
        <div class="form-actions">
            <button class="btn btn-success pull-right" type="submit">Guardar</button>
        </div>
        
    </form>
    
{% endblock %}